# Generated by Django 4.1.7 on 2023-03-03 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='multa',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cobro_de_multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cobrado', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.evento')),
                ('socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
