# Generated by Django 4.1.7 on 2023-02-20 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuota_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(default='Cuota extraordinaria para ', max_length=64)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField(default=datetime.date.today)),
                ('mora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_reg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuota_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Setiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('año', models.CharField(choices=[('2020', 2020), ('2021', 2021), ('2022', 2022), ('2023', 2023), ('2024', 2024), ('2025', 2025)], default='2023', max_length=4)),
                ('monto', models.PositiveSmallIntegerField(default=10)),
                ('est_reg', models.BooleanField(default=True)),
            ],
        ),
    ]
