# Generated by Django 4.1.7 on 2023-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota_social',
            name='nombre',
            field=models.CharField(default='01/2023', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
