# Generated by Django 4.1.7 on 2023-03-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuotas', '0002_cuota_social_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota_extra',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cuota_extra',
            name='nombre',
            field=models.CharField(default='Cuota extraordinaria para ', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Pago_cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_cuota', models.CharField(choices=[('CS', 'Cuota Social'), ('CE', 'Cuota Extra')], max_length=2)),
                ('cod_cuota', models.PositiveSmallIntegerField()),
                ('monto_cobrado', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('recibo', models.CharField(max_length=10)),
                ('exonerado', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
