# Generated by Django 4.1.7 on 2023-02-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='caso_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='inicio_de_vivencia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='vivencia_activa',
            field=models.BooleanField(default=False),
        ),
    ]
