# Generated by Django 4.1.7 on 2023-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_caso_social_socio_inicio_de_vivencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='exonerado',
            field=models.BooleanField(default=False),
        ),
    ]
