# Generated by Django 4.1.7 on 2023-02-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0003_terreno_disponible_alter_terreno_manzana'),
        ('socios', '0003_socio_exonerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='terreno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terrenos.terreno'),
        ),
    ]
