# Generated by Django 4.1.7 on 2023-02-20 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import terrenos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(choices=[('G', 'Mz G'), ('H', 'Mz H'), ('h', 'Mz H prima'), ('I', 'Mz I'), ('J', 'Mz J'), ('K', 'Mz K'), ('M', 'Mz M'), ('Ñ', 'Mz Ñ'), ('O', 'Mz O'), ('P', 'Mz P'), ('Q', 'Mz Q'), ('R', 'Mz R'), ('S', 'Mz S'), ('T', 'Mz T'), ('U', 'Mz U'), ('V', 'Mz V'), ('X', 'Mz X')], max_length=1)),
                ('lote', models.CharField(max_length=2)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('riesgo', models.BooleanField(default=False)),
                ('otros_usos', models.BooleanField(default=False)),
                ('vivencia', models.BooleanField(default=False)),
                ('observaciones', models.TextField(default='Ninguna')),
                ('est_reg', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(default=terrenos.models.Terreno.get_default_socio, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
