# Generated by Django 4.1.7 on 2023-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='propietario',
        ),
        migrations.AddField(
            model_name='terreno',
            name='nombre',
            field=models.CharField(default='A0', max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terreno',
            name='manzana',
            field=models.CharField(choices=[('A', 'Mz A'), ('B', 'Mz B'), ('G', 'Mz G'), ('H', 'Mz H'), ("H'", 'Mz H prima'), ('I', 'Mz I'), ('J', 'Mz J'), ('K', 'Mz K'), ('M', 'Mz M'), ('Ñ', 'Mz Ñ'), ('O', 'Mz O'), ('P', 'Mz P'), ('Q', 'Mz Q'), ('R', 'Mz R'), ('S', 'Mz S'), ('T', 'Mz T'), ('U', 'Mz U'), ('V', 'Mz V'), ('X', 'Mz X')], max_length=2),
        ),
    ]
