# Generated by Django 4.1.7 on 2023-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0003_terreno_disponible_alter_terreno_manzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='area',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=5),
        ),
    ]
